   version: '3.9'

   services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       container_name: fastapi_app
       ports:
         - "8000:8000" # Expose port aplikasi
       volumes:
         - .:/app # Sinkronisasi file lokal ke dalam container
       depends_on:
         - mongodb
       environment:
         - MONGO_URI=mongodb://mongodb:27017 # URL MongoDB di dalam jaringan Docker
       networks:
         - mynetwork

     mongodb:
       image: mongo:latest
       container_name: mongodb
       ports:
         - "27017:27017" # Expose port MongoDB
       volumes:
         - mongo_data:/data/db # Simpan data MongoDB ke volume
       networks:
         - mynetwork

   volumes:
     mongo_data:

   networks:
     mynetwork: